name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./Test.docker-compose.yml"
